debug: false #debug ??? ??? ???

management:
  endpoints:
    web:
      exposure:
        include: "*" #?????? ??? ?? ??? ? ??? ??.
logging:
  level:
    fastcampus.projectboard: debug
    org.springframework.web.servlet: debug #?? ??? ?? ??? fasle? ??? ? ??? ?? ??? ??? ??? ???? ??? ??.
    org.hibernate.type.descriptor.sql.BasicBinder: trace #queyry ??? ??? ? ?? ??
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: uno
    password: fantasy0258!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true #???? ?????? ???? ??
    hibernate.ddl-auto: create #?? ??, ???? ?? ??? ???? ??
    show-sql: true #?? ??? ??? ???
    properties: #springboot? ??? ?? ???? ?? ????? ?? ????
      hibernate:
        format_sql: true #????? ??? ???? ???? ??? ????
        default_batch_fetch_size: 100 #JPA?? JoinTable?? ???? ???? ??? ??? ??? ????? ?
  h2:
    console:
      enabled: false
  sql:
    init:
      mode: always #test???? ?? ??? ???.
  data.rest:
    base-path: /api
    detection-strategy: annotated
#yaml??? ---? ?? ?????
---
spring:
  config:
    activate:
      on-profile: testdb #testdb? ???? ?? ? ? ??? ???
#  datasource:
#    url: jdbc:h2:mem:board;mode=mysql
#    driverClassName: org.h2.Driver
#  sql:
#    init:
#      mode: always
#  test.database.replace: none #<-이거 없으면 위 설정값을 무시하고 그냥 컴퓨터 기본 설정값을 가지고 실행함.
